### ISSUE TITLE
unable to build the project

### ISSUE THREAD

**Issue by uday-lucky** [stntz/Xamarin.ZoomBinding#7] opened 2020-06-03 17:25 UTC
HI , i tried to build and deploy your project but after fixing  errors i am unable to fix this?

Xamarin.ZoomBinding-master/src/MobileRTC_Droid/Additions/MMBuddyItemComparator.cs(88,88): Error CS1503: Argument 2: cannot convert from 'Com.Zipow.Videobox.View.MM.MMContentSearchFilesAdapter.ContentFileComparator' to 'Java.Interop.IJavaPeerable' (CS1503) (MobileRTC_Droid)

**Comment by uday-lucky** [comment] 2020-06-04 08:26
i consumed xamarin.android.zoom nuget and its working fine. looking for ios nuget ? i couldn't find :(

**Comment by stntz** [comment] 2020-06-09 13:40
Duplicate of #8

**Closed by stntz** 2020-06-09 13:40 UTC

**Comment by stntz** [comment] 2020-06-09 19:03
@uday-lucky 

[https://github.com/stntz/Xamarin.ZoomBinding/issues/8#issuecomment-641510731](url)
